### ISSUE TITLE
Giving a steve skin if an account does not exist

### ISSUE THREAD

**Issue by TrollC** [surgeplay/Visage#32] opened 2018-05-04 08:54 UTC
Hello, I like to use Visage but there is a problem: when an account is not found no image is giving. I am hosting an offline mode server and when a player does not have a minecraft license no skin is given. It would be great if instead a Steve skin would be given. Thanks

**Comment by exaskye** [comment] 2018-05-04 10:58
Duplicate of #18

**Closed as completed by exaskye** 2018-05-04 10:58 UTC
Labels: s: Duplicate
