### ISSUE TITLE
A reason why you must allow lookup by username

### ISSUE THREAD

**Issue by ChefMC** [surgeplay/Visage#36] opened 2018-07-14 21:39 UTC
I host BungeeCord server with plugin ServerListPlus. But my BungeeCord server is in offline-mode, so players UUID's are wrong and I can't get Visage user head image for server list favicon. Single solution is getting player head image by his username.

It's safe because server list icon updating every 5-15 minutes and if player will see old icon for example 10 minutes, it is not critically. Please, allow this ability at least secretly

**Comment by falkreon** [comment] 2018-07-14 22:39
No, Visage "must" do no such thing. It's a free service, running free software, out of the generosity of the author's heart. The reasons for not doing so are clearly outlined on the Visage frontpage:

* Name changes are possible, and there's no guarantee that Mojang will continue to enforce uniqueness for usernames. Your lookups could be wrong forever, not just for 5-15 minutes, because it looks up the other player with that name.

* If you really wanted to do username lookups, it's better for your users and your security if you store stable mappings yourself. That way, even though you're in offline mode, you can still say "player X has uuid Y, and has had the same uuid Y every time." Visage wouldn't care about discrepancies in that data, but you certainly would.

* Every time you request an avatar or anything else Minecraft-related by username instead of UUID, Notch and Dinnerbone kill a sheep. Visage is a friend to sheep. It's sheep-friendly.

Aside from all that, it strikes me that if your players' UUIDs are wrong, then your skins are wrong *in-game* too. It's a bad situation all around.

**Comment by ChefMC** [comment] 2018-07-14 22:48
> then your skins are wrong in-game too

Oh, yep! I forgot :)
I even use SkinRestorer because of it

> Your lookups could be wrong forever, not just for 5-15 minutes, because it looks up the other player with that name.

No, because it doesn't matter if player will see other player skin for this few time. Keep in mind about his old nickname will be not available to be taken by other people for month, so it's impossible to see skin of other player in 15 minutes. + Nickname can be not taken by anyone for years

I see one solutions now. Make my web-site as proxy between Visage and Minecraft (PHP-script which normalizing UUIDs). But anyway, thanks for response

**Comment by exaskye** [comment] 2018-07-14 23:15
Duplicate of #18 - the offline use case to get the correct Steve/Alex skin based on inferred UUID is outlined there.

Using the username of an offline player to retrieve an online player's skin is inherently flawed, and is not a use case I will be supporting. If you absolutely want to do this, ignoring the fact it makes no goddamn sense, then yes, your best bet is a proxy to resolve usernames on your end. I'm choked for username lookups as is, and our username lookups are constantly down just because Mojang won't let us do any more of them due to the rate limiting.

And yes, while username changes are throttled to once a month, and the old username is locked during that time, *lookups in the interim period will fail*. For example, if my username is A and I change it to B, all lookups for user A will *immediately stop working*. After a month passes, someone else may change their name to A, in which case lookups will start working again, but *will point to the wrong player*.

**Closed as completed by exaskye** 2018-07-14 23:15 UTC
Labels: k: Question, s: Won't Fix
